pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/Dnyaneshwar9380/task-CICD.git'
            }
        }

        stage('Install Flask Dependencies') {
            steps {
                dir('Flask-App') {
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Install Express Dependencies') {
            steps {
                dir('Express-App') {
                    sh '''
                    npm install
                    '''
                }
            }
        }

        stage('Deploy Flask') {
            steps {
                dir('Flask-App') {
                    sh '''
                    pkill -f "python3 app.py" || true
                    nohup python3 app.py > flask.log 2>&1 &
                    '''
                }
            }
        }

        stage('Deploy Express') {
            steps {
                dir('Express-App') {
                    sh '''
                    pm2 delete express-app || true
                    pm2 start server.js --name express-app
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Deployment Successful!'
        }
        failure {
            echo 'Deployment Failed!'
        }
    }
}